[package]
name = "core"
edition = "2021"
version = "0.1.0"
authors = ["Alireza Baloochi <Dev.AlirezaBaloochi@gmail.com>"]
description = "Yugi is Static Site Generator"
license="MIT"

[lib]
name = "yugi"
path = "src/lib.rs"

[dependencies]
pulldown-cmark = "0.12.2"
